input:
  #samples_file: samples.wastewateronly.tsv
  samples_file: ../sampleset/samples.20210709_BPA73113-1417.tsv
  datadir: ../sampleset

#output:
  #snv: true
  #local: true
  #global: false
  #visualization: true
  #QA: true
