#variants_list:
#  - "B.1.1.7"
#  - "B.1.351"
#  - "P.1"
#  - "B.1.617.2"
#  - "B.1.617.1"
#  - "BA.1"
#  - "BA.2"
#  - "BA.4"
#  - "BA.5"
#  - "BA.2.75"
#  #-  "BA.2.75.2"
#  - "BQ.1.1"
#  - "XBB"

variants_pangolin:
  "al": "B.1.1.7"
  "be": "B.1.351"
  "ga": "P.1"
  "C36": "C.36.3"
  "ka": "B.1.617.1"
  "de": "B.1.617.2"
  "AY42": "AY.4.2"
  "B16173": "B.1.617.3"
  "om1": "BA.1"
  "om2": "BA.2"
  "om4": "BA.4"
  "om5": "BA.5"
  "om275": "BA.2.75"
  "om2752": "BA.2.75.2"
  "ombq11": "BQ.1.1"
  "om2121": "BA.2.12.1"
  "omxbb15": "XBB.1.5"
  "omxbb116": "XBB.1.16"
  "omxbb19": "XBB.1.9"
  "omxbb23": "XBB.2.3"

#variants_not_reported:
 # - "BA.2.75.2"
 # - "BA.2.12.1"
 # - "phe-BA.1"
 # - "phe-BA.2"
 # - "C.36.3"
 # - "B.1.617.3"
 # - "AY.4.2"
 # - "mu"
 # - "d614g"

start_date: "2020-12-08"

to_drop:
  - "subset"
 # - "shared"

locations_list:
  - "Lugano (TI)"
  - "Zürich (ZH)"
  - "Chur (GR)"
  - "Altenrhein (SG)"
  - "Laupen (BE)"
  - "Genève (GE)"
  - "Basel (catchment area ARA Basel)"
  - "Sierre/Noes (VS)"
  - "Porrentruy (JU)"
  - "Lausanne (Vidy)"
#  - "Lausanne (VD)"
#  - "Kanton Zürich"
